eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
server:
  port: 8087
spring:
  application:
    name: service-feignConfig

feign:
  hystrix:
    enabled: true
logging:
  level:
    com.michal.service.TestFeign: DEBUG
