server:
  port: 8082

spring:
  application:
    name: service-demo

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true